AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Gemfile'
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - test/*
    - bin/*

# Don't care how long lines are
Metrics/LineLength:
  Enabled: false

# Don't care how many lines blocks are
Metrics/BlockLength:
  Enabled: false

# Don't care how many lines methods are
Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Prefer tab indentation
Layout/Tab:
  Enabled: false

# Prefer [:foo, :bar, :baz] over %i[foo bar baz]
Style/SymbolArray:
  EnforcedStyle: brackets

# don't complain about "do_something and return if some_condition"
Style/AndOr:
  EnforcedStyle: conditionals

# Disable frozen-string-literal check
Style/FrozenStringLiteralComment:
  Enabled: false

# Don't care about documenting every class
Style/Documentation:
  Enabled: false

# Don't care about documenting all methods
Style/DocumentationMethod:
  Enabled: false

# Weirdly uses spaces, we prefer tabs
Layout/IndentHash:
  Enabled: false

# Weirdly uses spaces, we prefer tabs
Layout/IndentationWidth:
  Enabled: false

# Don't weirdly tab things like 'private'
Layout/AccessModifierIndentation:
  Enabled: false

# Force use of brackets for arrays of words
Style/WordArray:
  EnforcedStyle: "brackets"

# Consistent tabs for parameters
Layout/FirstParameterIndentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
